import "./globals.css";
import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";

const source_sans = Source_Sans_3({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "InterviewCompass",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={source_sans.className}>{children}</body>
    </html>
  );
}
